-- MANUALLY CREATING MISSING TABLES TO UNBLOCK LOCAL DEV
-- Version 5: Added ALL tables used in seed.sql with GENERATED BY DEFAULT

-- 1. cpi_countries
CREATE TABLE IF NOT EXISTS public.cpi_countries (
    country_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name text NOT NULL UNIQUE,
    currency text NOT NULL DEFAULT 'USD',
    currency_code text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 2. cpi_branches (Dependency for categories)
CREATE TABLE IF NOT EXISTS public.cpi_branches (
    branch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name text UNIQUE NOT NULL
);

-- 3. cpi_categories
CREATE TABLE IF NOT EXISTS public.cpi_categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id bigint REFERENCES public.cpi_branches(branch_id),
    category_name text NOT NULL,
    is_essential_category boolean DEFAULT false
);

-- 4. cpi_locations
CREATE TABLE IF NOT EXISTS public.cpi_locations (
    location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id bigint REFERENCES public.cpi_countries(country_id),
    location_name text NOT NULL,
    population integer
);

-- 5. cpi_establishments
CREATE TABLE IF NOT EXISTS public.cpi_establishments (
    establishment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id bigint REFERENCES public.cpi_countries(country_id),
    establishment_name text NOT NULL
);

-- 6. cpi_users
CREATE TABLE IF NOT EXISTS public.cpi_users (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name text,
    last_name text,
    email text,
    role text DEFAULT 'user',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT cpi_users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE public.cpi_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
ON public.cpi_users FOR SELECT 
USING (auth.uid() = user_id);

-- 7. cpi_products
CREATE TABLE IF NOT EXISTS public.cpi_products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name text NOT NULL,
    country_id bigint REFERENCES public.cpi_countries(country_id),
    category_id bigint REFERENCES public.cpi_categories(category_id),
    is_active_product boolean DEFAULT true
);

-- 8. cpi_tracking
CREATE TABLE IF NOT EXISTS public.cpi_tracking (
    tracking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.cpi_products(product_id),
    tracked_price numeric,
    location text,
    establishment_id bigint REFERENCES public.cpi_establishments(establishment_id),
    location_id bigint REFERENCES public.cpi_locations(location_id),
    country_id bigint REFERENCES public.cpi_countries(country_id),
    is_active_tracking boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- 9. cpi_volunteers
CREATE TABLE IF NOT EXISTS public.cpi_volunteers (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    status text DEFAULT 'pending',
    region text,
    country_id bigint REFERENCES public.cpi_countries(country_id),
    created_at timestamptz DEFAULT now()
);